### ISSUE TITLE
Path to books is hardcoded

### ISSUE THREAD

**Issue by Charles-Gagnon** [EmanueleMeazzo/SQL-Server-Diagnostic-Book#1]
Currently the extension is using a hardcoded path to the extensions folder to get the Notebooks

https://github.com/EmanueleMeazzo/SQL-Server-Diagnostic-Book/blob/master/src/jupyter-book.ts#L13

This isn't great for a couple of reasons :

1. The path might change - while that's pretty unlikely there's always the possibility we put the folder somewhere else or name it something different
2. This won't work for other versions of ADS - for example our insiders builds have a .azuredatastudio-insiders folder that extensions are installed into

Instead you should use https://github.com/microsoft/azuredatastudio/blob/main/src/vs/vscode.d.ts#L5616 (which comes from the context passed to the activate function)

**Comment by EmanueleMeazzo** [comment]
Hello Charles,

I'm no web developer, so I don't really know what's going on 🙃
I've created this extension using the new [ADS Extension Generator](https://cloudblogs.microsoft.com/sqlserver/2020/09/02/the-release-of-the-azure-data-studio-extension-generator-is-now-available/), the TS it's generated automatically, so it's maybe the case to report the issue up to the creators of that tool (?)

Anyway, I modified my code in order to use the extensionPath stored in the ExtensionContext, the code compiles correctly with vsce, the package is created, however, nothing happens when I launch the command in ADS

Can you help me understand what I'm missing here?

```
'use strict';

import * as vscode from 'vscode';
import * as azdata from 'azdata';
import * as path from 'path';
import * as fs from 'fs';
import * as os from 'os';

// This function looks in the user's default extensions folder for Azure Data Studio
// to find this extension and its packaged files. If it encounters an error, a
// message will appear in an error window.
const processNotebooks = (rootExtensionsFolder: string) => {
	
    let subExtensionFolder = getFolderContent(rootExtensionsFolder);

    try {
        subExtensionFolder.forEach(folderName => {
            findCorrectFolder(folderName, rootExtensionsFolder);
        });
    } catch (e) {
        vscode.window.showErrorMessage("Unable to access " + rootExtensionsFolder + ": " + e.message);
    }
}

// This function is called by processNotebooks to find the correct folder that contains
// this extension. If it is found, then it opens up the book in Azure Data Studio's
// native book viewlet.
const findCorrectFolder = (folderName: string, rootExtensionsFolder: string) => {
    let folderExt = path.basename(folderName).toLowerCase();

    if (folderExt.indexOf(('emanuelemeazzo.sql-server-diagnostic-book').toLowerCase()) > -1) {
        let fullFolderPath = path.join(rootExtensionsFolder, folderName);
        vscode.commands.executeCommand('bookTreeView.openBook', fullFolderPath, false);
    }
}

// This is a wrapper to read each subfolder in the extensions folder.
const getFolderContent = (folderPath: string) => {
    try {
        return fs.readdirSync(folderPath);
    } catch (e) {
        vscode.window.showErrorMessage("Unable to access " + folderPath + ": " + e.message);
        return [];
    }
}

// This function is called when you run the command `Launch Book: sql-server-diagnostic-book` from
// command palette in Azure Data Studio. If you would like any additional functionality
// to occur when you launch the book, add to the activate function.
export function activate(context: vscode.ExtensionContext) {
    context.subscriptions.push(vscode.commands.registerCommand('launchBook.sql-server-diagnostic-book', () => {
        processNotebooks(context.extensionPath);
    }));
}

```

**Comment by Charles-Gagnon** [comment]
Ah, thanks! I'll report that to the people working on the generator.

For your code above the path will be set to the root of your extension folder, so the code where you're iterating over the the folders in the path is going to be looking INSIDE your extension folder and thus never find the folder named `emanuelemeazzo.sql-server-diagnostic-book`

(context.extensionPath will be a value like this : `C:\Users\<name>\.azuredatastudio\extensions\emanuelemeazzo.sql-server-diagnostic-book`)

```
let subExtensionFolder = getFolderContent(rootExtensionsFolder);

    try {
        subExtensionFolder.forEach(folderName => {
            findCorrectFolder(folderName, rootExtensionsFolder);
        });
    } catch (e) {
        vscode.window.showErrorMessage("Unable to access " + rootExtensionsFolder + ": " + e.message);
    }
```

You can actually remove most of this logic and just have this in the activate function :

```
export function activate(context: vscode.ExtensionContext) {
    context.subscriptions.push(vscode.commands.registerCommand('launchBook.sql-server-diagnostic-book', () => {
        vscode.commands.executeCommand('bookTreeView.openBook', context.extensionPath, false);
    }));
```

and that should work.

**Comment by Charles-Gagnon** [comment]
https://github.com/llali/generator-azuredatastudio/issues/37

**Comment by EmanueleMeazzo** [comment]
Thank you very much for your support and for opening the issue with the generator team 🥇
